# LAB 3: LÀM SẠCH DỮ LIỆU CƠ BẢN

**Vấn đề 1: Tải dữ liệu và xử lý thiếu tiêu đề (Missing header)**

In [3]:
import pandas as pd

# Định nghĩa tên các cột cho dữ liệu
column_names = ['ID', 'Name', 'Age', 'Weight', 'm0006', 'm0612', 'm1218', 'f0006', 'f0612', 'f1218']

# Tải dữ liệu từ file csv, xử lý missing header và bỏ qua các dòng lỗi (bad lines)
df = pd.read_csv('/content/patient_heart_rate.csv', names=column_names, on_bad_lines='warn')

# Hiển thị 5 dòng đầu tiên
display(df.head())

/tmp/ipykernel_2773/3985871419.py:7: ParserWarning: Skipping line 17: expected 10 fields, saw 11

  df = pd.read_csv('/content/patient_heart_rate.csv', names=column_names, on_bad_lines='warn')

    ID            Name   Age      Weight m0006 m0612 m1218 f0006 f0612 f1218
0  1.0    Mickéy Mousé  56.0       70kgs    72    69    71     -     -     -
1  2.0     Donald Duck  34.0   154.89lbs     -     -     -    85    84    76
2  3.0      Mini Mouse  16.0         NaN     -     -     -    65    69    72
3  4.0  Scrooge McDuck   NaN       78kgs    78    79    72     -     -     -
4  5.0    Pink Panther  54.0  198.658lbs     -     -     -    69   NaN    75

**Vấn đề 2**

In [4]:
# Tách cột Name thành Firstname và Lastname
df[['Firstname', 'Lastname']] = df['Name'].str.split(expand=True, n=1)

# Xóa cột Name gốc
df = df.drop('Name', axis=1)

# Hiển thị kết quả
display(df.head())

,ID,Age,Weight,m0006,m0612,m1218,f0006,f0612,f1218,Firstname,Lastname
0,1.0,56.0,70kgs,72,69,71,-,-,-,Mickéy,Mousé
1,2.0,34.0,154.89lbs,-,-,-,85,84,76,Donald,Duck
2,3.0,16.0,NaN,-,-,-,65,69,72,Mini,Mouse
3,4.0,NaN,78kgs,78,79,72,-,-,-,Scrooge,McDuck
4,5.0,54.0,198.658lbs,-,-,-,69,NaN,75,Pink,Panther

**Vấn đề 3**

In [5]:
def convert_weight(weight):
    if pd.isna(weight):
        return weight

    weight_str = str(weight).lower()
    if 'kgs' in weight_str:
        return float(weight_str.replace('kgs', ''))
    elif 'lbs' in weight_str:
        # Chuyển đổi lbs sang kg: 1 lb = 0.453592 kg
        return float(weight_str.replace('lbs', '')) * 0.453592
    return float(weight_str)

# Áp dụng hàm chuyển đổi và cập nhật đơn vị
df['Weight'] = df['Weight'].apply(convert_weight)

# Hiển thị kết quả
display(df.head())

    ID   Age     Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0  1.0  56.0  70.000000    72    69    71     -     -     -    Mickéy    Mousé
1  2.0  34.0  70.256865     -     -     -    85    84    76    Donald     Duck
2  3.0  16.0        NaN     -     -     -    65    69    72      Mini    Mouse
3  4.0   NaN  78.000000    78    79    72     -     -     -   Scrooge   McDuck
4  5.0  54.0  90.109680     -     -     -    69   NaN    75      Pink  Panther

**Vấn đề 4**

In [7]:
# Xóa bỏ các dòng dữ liệu có chứa giá trị NaN
df.dropna(how='all', inplace=True)

# Hiển thị kết quả sau khi xóa
display(df)

/tmp/ipykernel_2773/2630848850.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(how='all', inplace=True)

,ID,Age,Weight,m0006,m0612,m1218,f0006,f0612,f1218,Firstname,Lastname
0,1.0,56.0,70.000000,72,69,71,-,-,-,Mickéy,Mousé
1,2.0,34.0,70.256865,-,-,-,85,84,76,Donald,Duck
5,6.0,52.0,85.728888,-,-,-,68,75,72,Huey,McDuck
6,7.0,19.0,56.000000,-,-,-,71,78,75,Dewey,McDuck
7,8.0,32.0,78.000000,78,76,75,-,-,-,Scööpy,Doo
10,9.0,52.0,85.728888,-,-,-,68,75,72,Huey,McDuck
11,10.0,12.0,45.000000,-,-,-,92,95,87,Louie,McDuck

**Vấn đề 5**

In [9]:
# Xử lý dữ liệu trùng lặp hoàn toàn
df.drop_duplicates(inplace=True)

# Hiển thị kết quả sau khi loại bỏ trùng lặp
display(df)

,ID,Age,Weight,m0006,m0612,m1218,f0006,f0612,f1218,Firstname,Lastname
0,1.0,56.0,70.000000,72,69,71,-,-,-,Mickéy,Mousé
1,2.0,34.0,70.256865,-,-,-,85,84,76,Donald,Duck
5,6.0,52.0,85.728888,-,-,-,68,75,72,Huey,McDuck
6,7.0,19.0,56.000000,-,-,-,71,78,75,Dewey,McDuck
7,8.0,32.0,78.000000,78,76,75,-,-,-,Scööpy,Doo
10,9.0,52.0,85.728888,-,-,-,68,75,72,Huey,McDuck
11,10.0,12.0,45.000000,-,-,-,92,95,87,Louie,McDuck

**Vấn đề 6**

In [10]:
# Xử lý ký tự non-ASCII trong cột Firstname và Lastname
df['Firstname'] = df['Firstname'].replace(r'[^\x00-\x7F]+', '', regex=True)
df['Lastname'] = df['Lastname'].replace(r'[^\x00-\x7F]+', '', regex=True)

# Hiển thị kết quả
display(df.head())

    ID   Age     Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0  1.0  56.0  70.000000    72    69    71     -     -     -     Micky     Mous
1  2.0  34.0  70.256865     -     -     -    85    84    76    Donald     Duck
5  6.0  52.0  85.728888     -     -     -    68    75    72      Huey   McDuck
6  7.0  19.0  56.000000     -     -     -    71    78    75     Dewey   McDuck
7  8.0  32.0  78.000000    78    76    75     -     -     -      Scpy      Doo

**Vấn đề 7: Xử lý Missing Values trên Age và Weight**

In [11]:
# 1. Thống kê dữ liệu thiếu
print("Thống kê dữ liệu thiếu:")
print(df[['Age', 'Weight']].isna().sum())

# 2. Xóa dòng nếu thiếu cả Age và Weight
df.dropna(subset=['Age', 'Weight'], how='all', inplace=True)

# 3. Thay thế Age thiếu bằng giá trị mean
# Chuyển đổi Age sang numeric nếu cần thiết trước khi tính mean
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
age_mean = df['Age'].mean()
df['Age'].fillna(age_mean, inplace=True)

# Hiển thị kết quả
display(df.head())
print(f"\nGiá trị Age dùng để thay thế (Mean): {age_mean}")

Thống kê dữ liệu thiếu:
Age       0
Weight    0
dtype: int64

/tmp/ipykernel_2773/1869186697.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(age_mean, inplace=True)

    ID   Age     Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0  1.0  56.0  70.000000    72    69    71     -     -     -     Micky     Mous
1  2.0  34.0  70.256865     -     -     -    85    84    76    Donald     Duck
5  6.0  52.0  85.728888     -     -     -    68    75    72      Huey   McDuck
6  7.0  19.0  56.000000     -     -     -    71    78    75     Dewey   McDuck
7  8.0  32.0  78.000000    78    76    75     -     -     -      Scpy      Doo

Giá trị Age dùng để thay thế (Mean): 36.714285714285715

**Vấn đề 8**

In [14]:
# Chuyển dữ liệu từ wide format sang long format

df = pd.melt(
    df,
    id_vars=["Firstname", "Lastname", "Age", "Weight"],
    value_vars=["m0006","m0612","m1218",
                "f0006","f0612","f1218"],
    var_name="Code",
    value_name="PulseRate"
)

# Tách giới tính
df["Sex"] = df["Code"].str[0]

# Tách thời gian
df["Time"] = df["Code"].str[1:]

# Đổi giới tính
df["Sex"] = df["Sex"].replace({
    "m":"Male",
    "f":"Female"
})

# Đổi mã thời gian
df["Time"] = df["Time"].replace({
    "0006":"00-06",
    "0612":"06-12",
    "1218":"12-18"
})

# Loại bỏ giá trị không hợp lệ
df["PulseRate"] = df["PulseRate"].replace("-", pd.NA)

# Chuyển PulseRate sang số
df["PulseRate"] = pd.to_numeric(
    df["PulseRate"],
    errors="coerce"
)

# Xóa các dòng không có PulseRate
df = df.dropna(subset=["PulseRate"])

# Đưa PulseRate về int
df["PulseRate"] = df["PulseRate"].astype(int)

# Loại bỏ cột Code
df = df.drop(columns=["Code"])

# Sắp xếp dữ liệu
df = df.sort_values(
    by=["Firstname","Lastname","Sex","Time"]
)

# Đánh lại chỉ số
df = df.reset_index(drop=True)

print(df)

   Firstname Lastname   Age     Weight  PulseRate     Sex   Time
0      Dewey   McDuck  19.0  56.000000         71  Female  00-06
1      Dewey   McDuck  19.0  56.000000         78  Female  06-12
2      Dewey   McDuck  19.0  56.000000         75  Female  12-18
3     Donald     Duck  34.0  70.256865         85  Female  00-06
4     Donald     Duck  34.0  70.256865         84  Female  06-12
5     Donald     Duck  34.0  70.256865         76  Female  12-18
6       Huey   McDuck  52.0  85.728888         68  Female  00-06
7       Huey   McDuck  52.0  85.728888         68  Female  00-06
8       Huey   McDuck  52.0  85.728888         75  Female  06-12
9       Huey   McDuck  52.0  85.728888         75  Female  06-12
10      Huey   McDuck  52.0  85.728888         72  Female  12-18
11      Huey   McDuck  52.0  85.728888         72  Female  12-18
12     Louie   McDuck  12.0  45.000000         92  Female  00-06
13     Louie   McDuck  12.0  45.000000         95  Female  06-12
14     Louie   McDuck  12.0  45.000000         87  Female  12-18
15     Micky     Mous  56.0  70.000000         72    Male  00-06
16     Micky     Mous  56.0  70.000000         69    Male  06-12
17     Micky     Mous  56.0  70.000000         71    Male  12-18
18      Scpy      Doo  32.0  78.000000         78    Male  00-06
19      Scpy      Doo  32.0  78.000000         76    Male  06-12
20      Scpy      Doo  32.0  78.000000         75    Male  12-18

11. Hãy khảo sát tỉ lệ dữ liệu thiếu trên biến huyết áp. Dữ liệu bị thiếu thì hãy xử lý bằng
phương pháp sau **bold text**

In [16]:
df = df.sort_values(
    by=['Firstname','Lastname','Sex','Time']
).reset_index(drop=True)

In [18]:
import pandas as pd
import numpy as np

for idx in df[df['PulseRate'].isna()].index:

    person = (
        (df['Firstname'] == df.loc[idx,'Firstname']) &
        (df['Lastname'] == df.loc[idx,'Lastname']) &
        (df['Sex'] == df.loc[idx,'Sex'])
    )

    person_data = df[person]

    person_idx = person_data.index.tolist()

    pos = person_idx.index(idx)

    value = np.nan

    # 1. Trung bình trước và sau
    if pos > 0 and pos < len(person_idx)-1:

        prev_val = df.loc[person_idx[pos-1],'PulseRate']
        next_val = df.loc[person_idx[pos+1],'PulseRate']

        if pd.notna(prev_val) and pd.notna(next_val):
            value = (prev_val + next_val)/2

    # 2. Trung bình 2 giá trị trước
    if pd.isna(value):

        if pos >= 2:

            p1 = df.loc[person_idx[pos-1],'PulseRate']
            p2 = df.loc[person_idx[pos-2],'PulseRate']

            if pd.notna(p1) and pd.notna(p2):
                value = (p1+p2)/2

    # 3. Trung bình 2 giá trị sau
    if pd.isna(value):

        if pos <= len(person_idx)-3:

            n1 = df.loc[person_idx[pos+1],'PulseRate']
            n2 = df.loc[person_idx[pos+2],'PulseRate']

            if pd.notna(n1) and pd.notna(n2):
                value = (n1+n2)/2

    # 4. Trung bình của người đó
    if pd.isna(value):

        mean_person = person_data['PulseRate'].mean()

        if pd.notna(mean_person):
            value = mean_person

    # 5. Trung bình theo giới tính
    if pd.isna(value):

        mean_sex = (
            df[df['Sex']==df.loc[idx,'Sex']]
            ['PulseRate']
            .mean()
        )

        if pd.notna(mean_sex):
            value = mean_sex

    # 6. Trung bình toàn bộ dữ liệu
    if pd.isna(value):

        mean_all = df['PulseRate'].mean()

        if pd.notna(mean_all):
            value = mean_all

    # 7. Giá trị ổn định y học
    if pd.isna(value):

        value = 75

    df.loc[idx,'PulseRate'] = round(value)

0

In [19]:
print(df['PulseRate'].isnull().sum())

0

12. Hãy rút gọn dữ liệu phù hợp và reindex lại dữ liệu. Sau đó, lưu trữ dữ liệu đã xử lý thành
công với tên file patient_heart_rate_clean.csv **bold text**

In [20]:
df = df[
    [
        'Firstname',
        'Lastname',
        'Age',
        'Weight',
        'Sex',
        'Time',
        'PulseRate'
    ]
]
df.reset_index(
    drop=True,
    inplace=True
)
print(df.head())
print(df.info())
df.to_csv(
    'patient_heart_rate_clean.csv',
    index=False
)

  Firstname Lastname   Age     Weight     Sex   Time  PulseRate
0     Dewey   McDuck  19.0  56.000000  Female  00-06         71
1     Dewey   McDuck  19.0  56.000000  Female  06-12         78
2     Dewey   McDuck  19.0  56.000000  Female  12-18         75
3    Donald     Duck  34.0  70.256865  Female  00-06         85
4    Donald     Duck  34.0  70.256865  Female  06-12         84
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Firstname  21 non-null     object
 1   Lastname   21 non-null     object
 2   Age        21 non-null     float64
 3   Weight     21 non-null     float64
 4   Sex        21 non-null     object
 5   Time       21 non-null     object
 6   PulseRate  21 non-null     int64
dtypes: float64(2), int64(1), object(4)
memory usage: 1.3+ KB
None